Siedlerchr/types-ol-ext

@types/ol-ext/featureanimation/featureAnimation.d.ts, @types/ol-ext/interaction/SelectCluster.d.ts, @types/ol-ext/interaction/Transform.d.ts, @types/ol-ext/style/FontSymbol.d.ts, @types/ol-ext/types.d.ts, package-lock.json, package.json
- bump ol-ext 3.1.19
- bump other packages
- fixes some type that find by `npm run lint`
- fixes FontSymbol types from my PR
=> bump to ol-ext 3.1.19 and bump all packages, fixes some types

.gitignore
Extend .gitignore with Webstorm specific files and directories.
=> Add Webstorm files and directories to .gitignore.

@types/ol-ext/interaction/Transform.d.ts
Make options optional, add event definitions and fix TSLint warnings.
=> Refactor Transform.d.ts

@types/ol-ext/control/EditBar.d.ts, @types/ol-ext/control/IsochroneGeoportail.d.ts, @types/ol-ext/control/Target.d.ts
=> #20: Fix 'npm run lint' errors

@types/ol-ext/control/Imageline.d.ts, @types/ol-ext/control/IsochroneGeoportail.d.ts, @types/ol-ext/control/LayerSwitcher.d.ts, @types/ol-ext/control/Notification.d.ts, @types/ol-ext/control/Overlay.d.ts, @types/ol-ext/control/Overview.d.ts, @types/ol-ext/control/Permalink.d.ts, @types/ol-ext/control/Print.d.ts, @types/ol-ext/control/PrintDialog.d.ts, @types/ol-ext/control/Profile.d.ts, package-lock.json, package.json
Add missing PrintDialog
Add pdfjs for pdf control
Not sure if we can make pdfjs a dev dependency
=> Fix existing controls

@types/ol-ext/control/Bar.d.ts, @types/ol-ext/control/Button.d.ts, @types/ol-ext/control/Toggle.d.ts, @types/ol-ext/filter/Base.d.ts, @types/ol-ext/filter/Mask.d.ts, @types/ol-ext/overlay/Popup.d.ts
@Siedlerchr From PR #23, I separated `@types/ol-ext` related commits to this PR, so could you check this a bit ?
- comment: https://github.com/Siedlerchr/types-ol-ext/pull/23#issuecomment-869073613
Thanks,
=> Fix type defs from examples

@types/ol-ext/render/Ordering.d.ts, @types/ol-ext/style/Chart.d.ts, @types/ol-ext/style/FillPattern.d.ts, @types/ol-ext/style/FlowLine.d.ts, @types/ol-ext/style/FontSymbol.d.ts, @types/ol-ext/style/Photo.d.ts, @types/ol-ext/style/Profile.d.ts, @types/ol-ext/style/Shadow.d.ts, @types/ol-ext/style/StrokePattern.d.ts, @types/ol-ext/style/style.d.ts
=> Fix styles

@types/ol-ext/render/Ordering.d.ts, @types/ol-ext/style/FontSymbol.d.ts
From PR #23, additional update for style/font examples.
=> Fix type defs from style/font example

@types/ol-ext/format/GeoJSONP.d.ts, @types/ol-ext/format/GeoJSONX.d.ts, @types/ol-ext/format/GeoRSS.d.ts, @types/ol-ext/geom/Dijskra.d.ts, @types/ol-ext/geom/GPAltiCode.d.ts, @types/ol-ext/geom/GeomUtils.d.ts, @types/ol-ext/geom/Scribble.d.ts, @types/ol-ext/geom/geohash.d.ts, @types/ol-ext/geom/sphere.d.ts
=> add missing format types

@types/ol-ext/interaction/Blob.d.ts, @types/ol-ext/interaction/CenterTouch.d.ts, @types/ol-ext/interaction/Clip.d.ts, @types/ol-ext/interaction/CopyPaste.d.ts, @types/ol-ext/interaction/CurrentMap.d.ts, @types/ol-ext/interaction/Delete.d.ts, @types/ol-ext/interaction/DragOverlay.d.ts, @types/ol-ext/interaction/DrawHole.d.ts, @types/ol-ext/interaction/DrawRegular.d.ts, @types/ol-ext/interaction/DrawTouch.d.ts, @types/ol-ext/interaction/DropFile.d.ts, @types/ol-ext/interaction/FillAttribute.d.ts, @types/ol-ext/interaction/Flashlight.d.ts, @types/ol-ext/interaction/FocusMap.d.ts, @types/ol-ext/interaction/GeolocationDraw.d.ts, @types/ol-ext/interaction/Hover.d.ts, @types/ol-ext/interaction/LongTouch.d.ts, @types/ol-ext/interaction/ModifyFeature.d.ts, @types/ol-ext/interaction/ModifyTouch.d.ts, @types/ol-ext/interaction/Offset.d.ts, @types/ol-ext/interaction/Ripple.d.ts, @types/ol-ext/interaction/SelectCluster.d.ts, @types/ol-ext/interaction/SnapGuides.d.ts, @types/ol-ext/interaction/SnapLayerPixel.d.ts, @types/ol-ext/interaction/Split.d.ts, @types/ol-ext/interaction/Splitter.d.ts, @types/ol-ext/interaction/Synchronize.d.ts, @types/ol-ext/interaction/TinkerBell.d.ts, @types/ol-ext/interaction/TouchCompass.d.ts, @types/ol-ext/interaction/UndoRedo.d.ts
Fixes #31 
TODO: Define events
=> [WIP] Fix interactions

@types/ol-ext/control/Search.d.ts, @types/ol-ext/control/SearchJSON.d.ts, @types/ol-ext/control/SearchNominatim.d.ts, examples/search/map.control.searchnominatim.ts
=> [examples] Check Search/Nominatim .etc examples

package.json
Fixes #47.
- Add empty `index.d.ts` file as entry point.
=> Add empty index.d.ts file as entry point

@types/ol-ext/filter/Crop.d.ts, @types/ol-ext/filter/Mask.d.ts, examples/filter/map.filter.crop.ts
@Siedlerchr I confirmed that Crop/Mask filter example works correctly with these changes.
---
Closes #54
=> Adjusted default export for Crop/Mask class

.prettierrc, @types/ol-ext/filter/Halftone.d.ts, @types/ol-ext/util/input/Color.d.ts, @types/ol-ext/util/input/PopupBase.d.ts, package.json
=> Add new halftone filter types

@types/ol-ext/control/EditBar.d.ts, @types/ol-ext/featureanimation/Path.d.ts, @types/ol-ext/overlay/Tooltip.d.ts, @types/ol-ext/style/Photo.d.ts, @types/ol-ext/util/input/Color.d.ts, examples/bar/map.control.editbar.ts, examples/interaction/map.interaction.drawregular.ts, examples/misc/map.input.ts, package-lock.json, package.json
=> Fix editon bar examples and interaction from master

@types/ol-ext/interaction/Clip.d.ts, @types/ol-ext/render/Cspline.d.ts, examples/geom/map.geom.cspline.ts, package-lock.json, package.json
Fixes #43 
add remove layers to interaction
@sanak  Seems like I need your help again here.. I am stuck in the example with the cspline function on geometry
The problem is that it is a method directly on a geometry object. I already added a module declaration to augment it, but I can't get my head around it. It would be really cool if you have an idea.
=> Try to add Cspline examples

@types/ol-ext/control/Dialog.d.ts, @types/ol-ext/control/Profile.d.ts, @types/ol-ext/control/ProgressBar.d.ts, @types/ol-ext/control/SwipeMap.d.ts, @types/ol-ext/interaction/Clip.d.ts, @types/ol-ext/interaction/ModifyFeature.d.ts, examples/misc/map.compare.ts, package-lock.json, package.json
Fixes #76 
Fixes #75 
Fixes #74
=> Update to ol3221

@types/ol-ext/control/Graticule.d.ts, @types/ol-ext/style/Photo.d.ts, @types/ol-ext/util/input/Collection.d.ts, package-lock.json, package.json
Add new properties and methods
=> Update to new ol-ext version

@types/ol-ext/control/Graticule.d.ts, @types/ol-ext/style/FillPattern.d.ts, @types/ol-ext/style/StrokePattern.d.ts, package-lock.json, package.json
=> Fix Pattern defs and Graticule setStyle

@types/ol-ext/control/GeoBookmark.d.ts, @types/ol-ext/control/Permalink.d.ts, @types/ol-ext/control/SearchGeoportail.d.ts, @types/ol-ext/filter/Base.d.ts, @types/ol-ext/filter/CSS.d.ts, @types/ol-ext/filter/CanvasFilter.d.ts, @types/ol-ext/filter/Clip.d.ts, @types/ol-ext/filter/Colorize.d.ts, @types/ol-ext/filter/Composite.d.ts, @types/ol-ext/filter/Fold.d.ts, @types/ol-ext/filter/Lego.d.ts, @types/ol-ext/filter/PencilSketch.d.ts, @types/ol-ext/filter/Pointillism.d.ts, @types/ol-ext/filter/SVGFilter.d.ts, @types/ol-ext/filter/Texture.d.ts, @types/ol-ext/interaction/DropFile.d.ts, @types/ol-ext/layer/GetPreview.d.ts, package-lock.json, package.json
=> Fix missing exports

@types/ol-ext/control/Bar.d.ts, @types/ol-ext/interaction/Transform.d.ts, examples/interaction/map.interaction.transform.ts, package-lock.json
=> fix transform interaction

@types/ol-ext/filter/Crop.d.ts, @types/ol-ext/filter/Mask.d.ts, @types/ol-ext/legend/Image.d.ts, @types/ol-ext/legend/Legend.d.ts, examples/filter/map.filter.crop.ts, package-lock.json, package.json
Add new image to legend
Fix constructor options in Legend
=> Add new parameters to Mask and filter

@types/ol-ext/geom/Scribble.d.ts, @types/ol-ext/interaction/SelectCluster.d.ts, @types/ol-ext/legend/Legend.d.ts, @types/ol-ext/style/Photo.d.ts, package-lock.json, package.json
Add missing property to options Fixes #111
=> Update to ol-ext 4.0.4

@types/ol-ext/style/Chart.d.ts
=> fix: correct Chart's Options interface. improve code style.

@types/ol-ext/control/Print.d.ts
The Print Options interface has some wrong type of properties. Please review and apply it.
=> Update PrintOptions interface

package.json
I'm not using jspdf. Thus, I don't want to install it plus its dependencies for typechecking.
<details>
```diff
diff --git a/yarn.lock b/yarn.lock
index 27f3d18..a4bb69e 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -2,13 +2,6 @@
-"@babel/runtime@^7.12.5", "@babel/runtime@^7.14.0":
-  version "7.23.4"
-  resolved "https://registry.yarnpkg.com/@babel/runtime/-/runtime-7.23.4.tgz#36fa1d2b36db873d25ec631dcc4923fdc1cf2e2e"
-  integrity sha512-2Yv65nlWnWlSpe3fXEyX5i7fx5kIKo4Qbcj+hMO0odwaneFjfXw5fdum+4yL20O0QiaHpia0cYQ9xpNMqrBwHg==
-  dependencies:
-    regenerator-runtime "^0.14.0"
-
"@esbuild/android-arm64@0.19.7":
version "0.19.7"
resolved "https://registry.yarnpkg.com/@esbuild/android-arm64/-/android-arm64-0.19.7.tgz#646156aea43e8e6723de6e94a4ac07c5aed41be1"
@@ -184,46 +177,9 @@
resolved …
```
=> Make jspdf a peerDependency

@types/ol-ext/map/PerspectiveMap.d.ts
It was expecting export default instead of simply export.
Fixes #146
=> Adding the fix to the error with PerspectiveMap.

@types/ol-ext/util/element.d.ts
I needed type definitions of `element.d.ts`.
Eventually that's also useful for others.
=> Adds element.d.ts

@types/ol-ext/control/Imageline.d.ts, @types/ol-ext/control/PrintDialog.d.ts, @types/ol-ext/control/PrintDialog2x.d.ts, @types/ol-ext/control/Profile.d.ts, @types/ol-ext/interaction/DrawHole.d.ts, @types/ol-ext/interaction/Offset.d.ts, @types/ol-ext/interaction/SelectCluster.d.ts, @types/ol-ext/interaction/SnapGuides.d.ts, @types/ol-ext/layer/AnimatedCluster.d.ts, @types/ol-ext/layer/Render3D.d.ts, @types/ol-ext/layer/SketchOverlay.d.ts, @types/ol-ext/source/BinBase.d.ts, @types/ol-ext/source/DFCI.d.ts, @types/ol-ext/source/DayNight.d.ts, @types/ol-ext/source/Delaunay.d.ts, @types/ol-ext/source/GeoRSS.d.ts, @types/ol-ext/source/GridBin.d.ts, @types/ol-ext/source/HexBin.d.ts, @types/ol-ext/source/Mapillary.d.ts, @types/ol-ext/source/TileWFS.d.ts, @types/ol-ext/source/WikiCommons.d.ts, examples/storymap/map.control.imageline.ts, examples/style/map.style.font.ts, package-lock.json, package.json, tsconfig.json
add set source method for cluster and adjust types
=> Update to ol ext 4.0.18 and ol 9.1

@types/ol-ext/source/GeoImage.d.ts
=> Make GeoImage mask optional

@types/ol-ext/control/Search.d.ts, package-lock.json, package.json
Fixes https://github.com/Siedlerchr/types-ol-ext/issues/178
Fix some build errors
=> Updated dependencies
